/**
 *  mutation-types.js
 *  Create By rehellinen
 *  Create On 2018/8/15 15:44
 */
export const types = {
  ADD_CART_GOODS: 'ADD_CART_GOODS',
  SELECT_ALL: 'SELECT_ALL',
  SAVE_CART_DATA: 'SAVE_CART_DATA',
  SAVE_CART_STORAGE: 'SAVE_CART_STORAGE',
  SET_ORDERS_CHANGE: 'SET_ORDERS_CHANGE',
  SET_LOADING_STATE: 'SET_LOADING_STATE',
  ADD_LOADED_PHOTOS: 'ADD_LOADED_PHOTOS'
}
